### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "jihsed1@gmail.com",
  "password": "jihed123",
  "roles": ["admin"]
}

###
### Register a new user with skills
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "farouk@gmail.com",
  "password": "Password123",
  "roles": ["user"],
  "skills": [
    {
      "name": "react",
      "description": "Modern JavaScript development",
      "proficiencyLevel": "intermediate"
    },
    {
      "name": "Python",
      "description": "Python programming",
      "proficiencyLevel": "beginner"
    }
  ],
  "desiredSkills": [
    {
      "name": "React",
      "description": "React.js framework",
      "desiredProficiencyLevel": "advanced"
    }
  ]
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jihed1@gmail.com",
  "password": "jihed123"
}

###
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2FhNjYxODU4MDE4NjFiNWM1MjA3NDciLCJlbWFpbCI6ImppaGVkMUBnbWFpbC5jb20iLCJpYXQiOjE3MzkyNzE5ODIsImV4cCI6MTczOTI3Mjg4Mn0.yHW5k1yOk9a4EO6sOVM8hDpuR89Ckq63DuFN7lEp4TI